import type { GameModeConfig, GameModeId } from "@/types/chess";

export const GAME_MODES: Record<GameModeId, GameModeConfig> = {
  classic: {
    id: "classic",
    name: "Classic Chess",
    seats: ["white", "black"],
    teams: ["white", "black"],
    playerCount: 2,
    rated: true,
    timeControl: "10+0",
    description: "Standard 1v1 chess with a clean server-ready state model.",
    category: "ranked",
    format: "1v1",
    available: false,
  },
  rapid: {
    id: "rapid",
    name: "Rapid Ladder",
    seats: ["white", "black"],
    teams: ["white", "black"],
    playerCount: 2,
    rated: true,
    timeControl: "15+10",
    description: "A slower rated mode profile that can get its own queue and leaderboard.",
    category: "ranked",
    format: "1v1",
    available: false,
  },
  bot: {
    id: "bot",
    name: "Bot Practice",
    seats: ["white", "black"],
    teams: ["white", "black"],
    playerCount: 2,
    rated: false,
    timeControl: "10+0",
    description: "Practice against a bot at a difficulty that suits you.",
    category: "practice",
    format: "1v1",
    available: true,
  },
  "two-v-two-bot": {
    id: "two-v-two-bot",
    name: "2v2 vs Bot",
    seats: ["white-lead", "white-partner", "black-bot-lead", "black-bot-partner"],
    teams: ["white", "black"],
    playerCount: 4,
    rated: false,
    timeControl: "shared",
    description: "Team chess against two coordinated bots.",
    category: "team",
    format: "2v2",
    available: true,
  },
  "two-v-two-players": {
    id: "two-v-two-players",
    name: "2v2 vs Players",
    seats: ["white-lead", "white-partner", "black-lead", "black-partner"],
    teams: ["white", "black"],
    playerCount: 4,
    rated: false,
    timeControl: "shared",
    description: "Team chess with two players on each side.",
    category: "team",
    format: "2v2",
    available: false,
  },
  "coop-preview": {
    id: "coop-preview",
    name: "Co-op Preview",
    seats: ["white-lead", "white-partner", "black-lead", "black-partner"],
    teams: ["white", "black"],
    playerCount: 4,
    rated: false,
    timeControl: "shared",
    description: "A future-ready shell for team chess without changing the room UI contract.",
    category: "social",
    format: "2v2",
    available: false,
  },
};

export const modeList = Object.values(GAME_MODES);
